### ISSUE TITLE
[Home Assistant] Support calling Services.

### ISSUE THREAD

**Issue by frakman1** [raycast/extensions#11487]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

I have defined shell command services within HA e.g.
```yaml
# Exposes service shell_command.xxxx
shell_command:
  print_date: touch /tmp/$(date +"%m_%d_%Y")
  snapshot_nest_frontdoor: /bin/bash -c /config/nest_snapshot.sh
  reset_modem: curl -u xxx:'xxx' --location --request GET 'http://xxx/overview?reset=Reset' 
```
These are all callable within HA from automations or the dashboard. e.g.
<img width="472" alt="image" src="https://github.com/raycast/extensions/assets/5826484/16235de5-8353-4ef9-b83c-cbc23e32affd">

It would be nice if I can call my HA services from within Raycast since most apps that use the HA API support calling services.

I realize that many services have associated input that might be hard to implement in an Extension but these services I am making take no input.

### Who will benefit from this feature?

Additional functionality into HA
