### ISSUE TITLE
[Docker] Starting a project should call a compose command instead of starting all containers seperately

### ISSUE THREAD

**Issue by iamrgroot** [raycast/extensions#15911]
### Extension

https://www.raycast.com/priithaamer/docker

### Description

Currently, when listing the Docker projects, running the start all command will start all containers separately. However, when you have dependent containers that include health checks, this tries to start the dependent container while the dependency is not healthy yet. The only way to start them all correctly is to wait and then try again.

### Who will benefit from this feature?

Docker compose users that use `depends_on` and `healthcheck`

### Anything else?

This issue on dockerode is relevant and could be used for a solution: https://github.com/apocas/dockerode/issues/547

Example docker compose:

```yml
services:
  node:
    image: node
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - application

  mysql:
    image: mysql
    networks:
      - application
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "-ppassword", "ping"]

networks:
  application:
```

Let me know if this is something I contribute myself 😄
