### ISSUE TITLE
[Model Context Protocol Registry] Server Fails to Install with `Read-only file system`

### ISSUE THREAD

**Issue by csaper** [raycast/extensions#19571]
### Extension

https://www.raycast.com/raycast/model-context-protocol-registry

### Raycast Version

1.99.3

### macOS Version

15.5

### Description

Upon attempting to install the **`@pydantic/mcp-run-python`** MCP server, the process fails with the following error:
```
Reason: [0m[1m[31merror[0m: Creating '/node_modules/.deno/node_modules'
    0: Read-only file system (os error 30), code: 1 
Domain: mcp
Time: 01:39:05.763
Underlying: 
  Domain: RaycastMCP.MCPClientError 0
```

![mcp-run-python MCP server installation failure](https://github.com/user-attachments/assets/14767ff4-d78b-4799-bbcd-23bc9d184376)

I have reproduced this consistently over a multi-week span. Of the dozen or so MCP servers I have installed via this extension, this is the only one that failed on me -- though note that this is the only of them that executes on the Deno runtime (vs Node or Bun.)

Per [Pydantic's documentation](https://ai.pydantic.dev/mcp/run-python/), I have tested running the server directly via CLI as follows:
```bash
deno run \
  -N -R=node_modules -W=node_modules --node-modules-dir=auto \
  jsr:@pydantic/mcp-run-python stdio
```
This has resulted in fully successful tool calls. Deno v2.3.3 is installed.

### Steps To Reproduce

1. Run `Search Servers (Model Context Protocol Registry)` command
2. In the 'Official' list, select `Pydantic Run Python`, then `Install Server...`, and choose `Raycast`
3. On the 'Install MCP Server' dialog make no changes to the server configuration. The default configurations are set as follows:
    - Icon: **MCP**
    - Name: **Pydantic Run Python**
    - Command: **deno**
    - Arguments: **run -N -R=node_modules -W=node_modules --node-modules-dir=auto jsr:@pydantic/mcp-run-python stdio**
    - Environment: _none_
    - Description: **The MCP Run Python package is an MCP server that allows agents to execute Python code in a secure, sandboxed environment. It uses Pyodide to run Python code in a JavaScript environment with Deno, isolating execution from the host system.**
4. Select `Install`
5. Immediately the installation will error with the following message:
    ```
    Reason: [0m[1m[31merror[0m: Creating '/node_modules/.deno/node_modules'
        0: Read-only file system (os error 30), code: 1 
    Domain: mcp
    Time: 01:39:05.763
    Underlying: 
	    Domain: RaycastMCP.MCPClientError 0
    ```

### Current Behaviour

Installation of `Pydantic Run Python` MCP server fails

### Expected Behaviour

Installation of `Pydantic Run Python` MCP server succeeds
