### ISSUE TITLE
[Google Search] failed, reason: self- signed certificate

### ISSUE THREAD

**Issue by Go2Heart** [raycast/extensions#3938]
### Extension

https://www.raycast.com/mblode/google-search

### Description

<img width="745" alt="image" src="https://user-images.githubusercontent.com/71871209/208250557-a989f8ce-f061-476b-85f8-c5d5f437218c.png">

Trying to utilize the new proxy function but failed as in the picture. What to be set on the certificate option? I am using http proxy on [localhost:port]

**Comment by fe9lix** [comment]
Hi! Could you share more details about your setup? Specifically:

- your proxy settings (hover over the checkbox "Use System Network Preferences" in Raycast Advanced Preferences)
- some details on what kind of proxy you're using and how you run it?
- your certificate settings? (your certificate settings in Raycast Advanced Preferences and what kind of certificate you've configured)

There's currently also a bug that will be fixed with the next release by the end of the week (though it might be unrelated to the issue you're seeing here.)

**Comment by fe9lix** [comment]
There are two issues: 

- One is a current Raycast bug that would try to use https for as secure proxy URL but only the http protocol is supported – this will be fixed with the next release later this week.
- Regarding the certificate: could you share more details about your local proxy? Apparently there's an https server with a self-signed certificate running?

**Comment by Go2Heart** [comment]
I am using Clash Premium[https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features] for my local proxy. And I use Clash for Windows[https://github.com/Fndroid/clash_for_windows_pkg] as the GUI for the proxy service. And I don't think I have done something about self-signed certificate while setting the local proxy up.

**Comment by fe9lix** [comment]
Could you share your Clash config? (You can leave out the parts that are irrelevant...)

**Comment by Go2Heart** [comment]
`port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
mixin:
  dns:
    enable: true
    listen: :53
    default-nameserver:
      - 223.5.5.5
      - 1.1.1.1
    enhanced-mode: redir-host
    nameserver:
      - 223.5.5.5
      - 223.6.6.6
      - https://223.5.5.5/resolve
    fallback:
      - 1.1.1.1
      - 208.67.220.222:5353
      - https://dns.rubyfish.cn/dns-query
      - https://doh.opendns.com/dns-query
      - tls://1.1.1.1:853
    fallback-filter:
      geoip: true
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    macOS-auto-route: true
    macOS-auto-detect-interface: true`

**Comment by Go2Heart** [comment]
```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
mixin:
  dns:
    enable: true
    listen: :53
    default-nameserver:
      - 223.5.5.5
      - 1.1.1.1
    enhanced-mode: redir-host
    nameserver:
      - 223.5.5.5
      - 223.6.6.6
      - https://223.5.5.5/resolve
    fallback:
      - 1.1.1.1
      - 208.67.220.222:5353
      - https://dns.rubyfish.cn/dns-query
      - https://doh.opendns.com/dns-query
      - tls://1.1.1.1:853
    fallback-filter:
      geoip: true
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    macOS-auto-route: true
    macOS-auto-detect-interface: true
```
