### ISSUE TITLE
[Espanso] Improvements to match match insertion

### ISSUE THREAD

**Issue by nbbaier** [raycast/extensions#9184]
### Extension

https://www.raycast.com/kud/espanso

### Description

Currently, the Espanso extension does expand/evaluate variables in a match's `replace` field. For example, for the match:

```yaml
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%M/%d/%Y"
```

Inserts the current date if triggered via espanso itself, but if inserted from the Raycast extension will insert the string `{{mydate}}`. It would be nice to have the same behavior across both experiences.

This should be more feasible now given #9101 because search draws directly the configuration files.

The easiest way of implementing this is probably checking if a match has any `vars` and if it does, using `espanso match exec --trigger`

### Anything else?

I'm happy to work on this myself, just wanted to submit the feature request/idea to see if there were comments from @kud or others!
